version: "3.7"

services:
  database:
    container_name: compemp
    image: postgres
    restart: unless-stopped
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=compemp
      - POSTGRES_USER=compemp
    ports:
      - "5432:5432"